### ISSUE TITLE
Feedback onderzoeksvraag

### ISSUE THREAD

**Issue by TimvanAlphen** [lars-ruijs/functional-programming#2]
Leuke onderzoeksvraag! Maar ik weet niet hoe werkelijk het is dat meer oplaadpalen ook echt meer brandgevaar betekend. Miss kun je een dataset vinden over autobranden en dan gaan kijken naar hoeveel hiervan elektrisch waren. Maar miss is dit heel lastig te vinden. Ik denk dat je nu nog te veel uitgaat van de conclusie dat meer oplaadpalen meer brand is.

Je kan miss kijken naar stel er is een brand in de parkeergarage, hoeveel uitgangen zijn er? En hoe kan een invalide veilig wegkomen? Iets als: Hoe veilig zijn parkeergarages bij een brand?

**Comment by lars-ruijs** [comment]
Bedankt voor je feedback Tim! Ik heb gezocht naar andere datasets over brandveiligheid, maar kon helaas niks interessants vinden. Ook de RDW heeft hier geen bruikbare data over. Ik heb mijn onderzoeksvraag daarom aangepast naar een heel ander onderwerp (zie readme). Tevens heb ik deelvragen, assumpties en een schets toegevoegd. Ik verwacht dat de nieuwe vraag beter te visualiseren is.

**Comment by TimvanAlphen** [comment]
👍
