### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by TimvanAlphen** [lars-ruijs/functional-programming#4]
## Repo + Readme

* Gitignore. ✔️
* Geen junk geupload. ✔️
* Repo heeft discription. ✔️
* Research question is beschreven data is aanwezig maar moet worden vernieuwd. Sketch niet aanwezig.
* Gebruikte data kan gedetailleerder worden beschreven.
* Geen link naar functional pattern.
* Geen plagiaat. ✔️

## Wiki

* Debrief is aanwezig. ✔️
* Datacleaning is goed beschreven. ✔️
* Gebruik van functional patterns is beschreven ✔️
* In de refresh-topics is te zien dat er veel vooruitgang is. ✔️

## Wiki Code

* Code flow is duidelijk. De code en het gebruik ervan staat netjes beschreven. ✔️
* Belangrijkste code staat niet bovenaan.
* De meeste code is opgedeeld in functies. .map en .filter worden gebruikt. 
* .map word correct gebruikt. ✔️
* Vooruitgang is zichtbaar. .map en .filter worden telkens op complexere code toegepast. ✔️
* Namen als: Datasleutel en waarde worden gebruikt waardoor de code algemeen is en herbruikbaar. Deze namen zijn misschien niet beschrijvend genoeg om door een ander te begrijpen.
* Code is functioneel. Er word gebruik gemaakt van functies, .map en .filter. Code is consistent. De code is herbruikbaar. Sommige namen zijn misschien te algemeen waardoor ze niet meteen duidelijk zijn.

(Heel veel voortgang voor een beginner. Principes worden snel opgepikt en toegepast 👍).

**Comment by lars-ruijs** [comment]
Bedankt voor de peer review! 

- De onderzoeksvraag heb ik gewijzigd en ik heb een bijbehorende schets toegevoegd (zie #2)
- Ik heb de data die ik wil gebruiken duidelijker omschreven, inclusief de te verwachten output. 
- Er is een sectie + link toegevoegd naar een van de functional patterns.
- Ik heb een sectie met gebruikte bronnen toegevoegd.
- De functies worden bovenaan in de code aangeroepen en de functies zelf staan onderaan.
- Ik heb de namen van de functies, parameters en variabelen in de uiteindelijke code van [script.js ](https://github.com/lars-ruijs/functional-programming/blob/main/survey-cleaning/scripts/script.js) aangepast naar algemenere (Engelstalige) termen. Ik hoop dat deze nu beter te begrijpen/duidelijker zijn.
