### ISSUE TITLE
Feedback op hoofdvraag/deelvragen

### ISSUE THREAD

**Issue by gijslaarman** [lars-ruijs/functional-programming#5]
Hey Lars,

Interessante hoofdvraag! Ik vraag mij alleen af wat het verband tussen de branden en garages is. Volgens mij wordt in jouw gelinkte artikel bedoeld dat het aan de elektrische auto's ligt die in brand kunnen vliegen en geen enkele garage daar goed tegen is bestemd. Misschien is een betere vraag in de richting: Waar kun je beter wél je elektrische auto parkeren, en op basis daarvan een aantal criteria uitzoeken. Of nog gekker "Waar staat jouw auto (benzine, diesel of elektrisch) veiliger i.v.m. de brandveiligheid en oplaaiende branden van elektrische auto's. En dat dan op basis van hoeveel oplaadpunten er zijn in garages (geen = beter, of oplaadpunten dichterbij de ingang = beter) een conclusie trekken.

Veel succes en ben benieuwd naar het eindresultaat 👍

**Comment by lars-ruijs** [comment]
Bedankt voor de feedback! Ik heb mijn onderzoeksvraag inmiddels aangepast naar een heel ander onderwerp (zie readme). Het onderwerp brandveiligheid bleek erg lastig te zijn om uit te werken als visualisatie. Ook ben ik niet verder gegaan met het onderwerp "elektrische auto" omdat dit al door veel anderen wordt gedaan. Ik heb bij het nieuwe concept nu ook deelvragen, assumpties en een schets toegevoegd. Ik verwacht dat de nieuwe vraag beter te visualiseren is.
